server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_PREFIX}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false

spring:
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          issuer-uri: https://sso.prasadpsycho.industrialdata.in/

  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_ACCESS_USERNAME}
    password: ${MQ_ACCESS_PASSWORD}
    ssl:
      enabled: ${MQ_SSL_ENABLED}
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5

  data:
    mongodb:
      uuid-representation: standard
      auto-index-creation: true
      uri: ${DB_CONNECTION_STRING}

  application:
    name: document_service

  main:
    banner-mode: off

logging:
  pattern:
    console: "%clr(%5p) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
        internal:
          InstanceMetadataServiceResourceFetcher: ERROR
