server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_PREFIX}

logging:
  pattern:
    console: "%clr(%5p) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: ${LOG_LEVEL}

springdoc:
  api-docs:
    path: /endpoints/docs

spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${CLIENT_ID}
        app-id-uri: ${APP_ID_URI}

  liquibase:
    enabled: false
    parameters:
      uuidColumnType: BINARY(16)
  main:
    banner-mode: off
  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
      jdbc:
        time_zone: "Asia/Kolkata"
      jakarta:
        persistence:
          sharedCache:
            mode: ALL

    open-in-view: false
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
sentry:
  dsn: ${SENTRY_DSN}
  environment: ${ENVIRONMENT}
  traces-sample-rate: 1.0


