server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_PREFIX}

springdoc:
  api-docs:
    path: /endpoints/docs

spring:
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          issuer-uri: https://sso.prasadpsycho.industrialdata.in/

  data:
    mongodb:
      uuid-representation: standard
      auto-index-creation: true
      uri: ${DB_CONNECTION_STRING}

  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_ACCESS_USERNAME}
    password: ${MQ_ACCESS_PASSWORD}
    ssl:
      enabled: ${MQ_SSL_ENABLED}
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5

  main:
    banner-mode: off

cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: AKIA24RZRLS7UMF4IC7G
      secretKey: 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

application:
  bucket:
    name: pp-service-images
