server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_PREFIX}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
spring:
  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_ACCESS_USERNAME}
    password: ${MQ_ACCESS_PASSWORD}
    ssl:
      enabled: ${MQ_SSL_ENABLED}
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5
  main:
    banner-mode: off

  application:
    name: notification-service
    admin:
      enabled: false

  aop:
    auto: false

  jmx:
    enabled: false

  sql:
    init:
      enabled: false

logging:
  pattern:
    console: "%clr([%5p]) %clr(%d{yy-MM-dd HH:mm:ss}){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
