server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_PREFIX}

spring:
  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_ACCESS_USERNAME}
    password: ${MQ_ACCESS_PASSWORD}
    ssl:
      enabled: ${MQ_SSL_ENABLED}
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5
  jmx:
    enabled: false

  application:
    name: credit-service

  data:
    mongodb:
      uuid-representation: standard
      auto-index-creation: true
      uri: ${DB_CONNECTION_STRING}
  main:
    banner-mode: off
    log-startup-info: false
