name: simple shell actions manual workflow
on:
  repository_dispatch:
    types: [build]

jobs:
  simple-command-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple command
        run: pwd
      - name: checkout repo
      - uses: actions/checkout@v3