# name: ci_for_artifact
# on:
#   push:
#     branches: [ main ]
# jobs:
#   job1:
#     name: add_3_and_7
#     runs-on: ubuntu-latest
#     steps:
#       - shell: bash
#         run: |
#           echo `expr 3 + 7` > math.txt

#       - name: upload_artifact
#       - uses: actions/upload-artifact@v3
#         with:
#             name: math-artifact
#             path: math.txt

#   # job2:
#   #   name: multiply_by_9
#   #   needs: job1
#   #   run-on: ubuntu_latest
#   #   steps:
#   #      - name: download_math_result_for_job1
#   #      - uses: actions/download-artifact@v3
#   #        with:
#   #           name: math-artifact

#   #      - shell: bash
#   #      - run: | 
#   #           value=`cat math.txt`
#   #           echo `expr $value  \*  9` > math.txt
#   #      - name: upload math result for job2
#   #      - uses: actions/upload-artifact@v3
#   #        with:
#   #           name: math-artifact
#   #           path: math.txt
#   # job3:
#   #   name: display_result
#   #   needs: job2
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #      - name : download math result for job2
#   #      - uses: actions/download-artifact@v3
#   #        with:
#   #           name: math-artifact
#   #      - shell: bash
#   #      - run: | 
#   #           value=`cat math.txt`
#   #           echo the result is $value