name: Ci
on: 
    repository_dispatch:
        types: [ build ]
jobs: 
    job1:
      runs-on: ubuntu-latest
      steps: 
        - name: code checkout 
          uses: actions/checkout@v3
        - name: run linux commands
          run: | 
            pwd
            ls -al
            whoami