name: checkout using github actions
on:
  push:
    branches: 
        - 'main'
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout 
        uses: actions/checkout@v3

      - name: Debug Step list all files
        shell: bash
        run: |
          echo "Hello world"
          ls -al