name: list_file_workflow
on: 
  push:
    branches: [ "main" ]

jobs: 
  List_changed_files:
    runs-on: ubuntu-latest
    steps:
      - name: step_name_list_files
        run: 
          pwd
          ls -ltr

      - name: chekout action
        uses: actions/checkout@v2


       - name: step_name_list_files_after_checkout
         run: 
           pwd
           ls -ltr